### ISSUE TITLE
Icon not found (IR2 2.3.2)

### ISSUE THREAD

**Issue by Edalbrelord** [nicklatkovich/fmod-ir2-rubber-tree-selective-breeding#1]
https://github.com/nicklatkovich/fmod-ir2-rubber-tree-selective-breeding/blob/448dff30ff4dcc24562ddff4868681aa5fb86356/data.lua#L62

The icon forestry-background is not available in IR2 2.3.2. Can this icon be replaced with perhaps forestry-overlay?

**Comment by nicklatkovich** [comment]
Thanks for the bug report. Fixed.
